# Generated by Django 3.0.7 on 2020-06-04 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.IntegerField(unique=True)),
                ('train_name', models.CharField(max_length=256, unique=True)),
                ('train_path', models.CharField(max_length=256)),
                ('start_time', models.TimeField()),
                ('total_duration', models.TimeField()),
                ('train_class', models.CharField(choices=[('RJ', 'Rajdhani'), ('PS', 'Passenger'), ('SD', 'Satabdi')], default='PS', max_length=2)),
                ('days', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('duration', models.TimeField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainroutes.Route')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainroutes.Train')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='dest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destidtostation', to='trainroutes.Station'),
        ),
        migrations.AddField(
            model_name='route',
            name='src_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srcidtostation', to='trainroutes.Station'),
        ),
    ]
