# Generated by Django 3.0.6 on 2020-06-07 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.IntegerField(unique=True)),
                ('train_name', models.CharField(max_length=256, unique=True)),
                ('train_path', models.CharField(max_length=256)),
                ('train_class', models.CharField(choices=[('RJ', 'Rajdhani'), ('PS', 'Passenger'), ('SD', 'Satabdi')], default='PS', max_length=2)),
                ('days', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.IntegerField()),
                ('reached_day', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('reached_time', models.TimeField()),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('duration', models.TimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainroutes.Train')),
            ],
        ),
    ]
